//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCourses.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CourseInstructors")]
    public partial class CourseInstructor
    {
        public int CoursesID { get; set; }
        public int PersonsID { get; set; }
        public int Utility { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Person Person { get; set; }
    }
}
