//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCourses.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentGrade
    {
        [Key]
        public int EnrollmentID { get; set; }
        public int CoursesID { get; set; }
        public int StudentID { get; set; }
        public Nullable<decimal> Grade { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Person Person { get; set; }
    }
}
